[2023-07-22T11:19:40.021+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:19:40.029+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/bs_tweets.py for tasks to queue
[2023-07-22T11:19:40.031+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:19:40.030+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:19:40.176+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:19:40.172+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/bs_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bs_tweets.py", line 14, in <module>
    DATASET_ID = Variable.get("DATASET_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable DATASET_ID does not exist'
[2023-07-22T11:19:40.180+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:19:40.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/bs_tweets.py took 0.227 seconds
[2023-07-22T11:20:10.474+0000] {processor.py:157} INFO - Started process (PID=294) to work on /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:20:10.475+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/bs_tweets.py for tasks to queue
[2023-07-22T11:20:10.477+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:20:10.477+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:20:10.506+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:20:10.503+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/bs_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bs_tweets.py", line 14, in <module>
    DATASET_ID = Variable.get("DATASET_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable DATASET_ID does not exist'
[2023-07-22T11:20:10.508+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:20:10.531+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/bs_tweets.py took 0.062 seconds
[2023-07-22T11:20:41.045+0000] {processor.py:157} INFO - Started process (PID=319) to work on /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:20:41.050+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/bs_tweets.py for tasks to queue
[2023-07-22T11:20:41.052+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:20:41.051+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:20:41.086+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:20:41.084+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/bs_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bs_tweets.py", line 14, in <module>
    DATASET_ID = Variable.get("DATASET_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable DATASET_ID does not exist'
[2023-07-22T11:20:41.087+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:20:41.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/bs_tweets.py took 0.066 seconds
[2023-07-22T11:21:11.203+0000] {processor.py:157} INFO - Started process (PID=344) to work on /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:21:11.205+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/bs_tweets.py for tasks to queue
[2023-07-22T11:21:11.206+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:21:11.206+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:21:11.245+0000] {logging_mixin.py:150} INFO - [2023-07-22T11:21:11.243+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/bs_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/bs_tweets.py", line 14, in <module>
    DATASET_ID = Variable.get("DATASET_ID")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable DATASET_ID does not exist'
[2023-07-22T11:21:11.246+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/bs_tweets.py
[2023-07-22T11:21:11.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/bs_tweets.py took 0.066 seconds
