[2023-07-22T08:07:34.646+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_final_project.spark_cleansing_task manual__2023-07-22T08:06:16.970985+00:00 [queued]>
[2023-07-22T08:07:34.662+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_final_project.spark_cleansing_task manual__2023-07-22T08:06:16.970985+00:00 [queued]>
[2023-07-22T08:07:34.663+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-22T08:07:34.690+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): spark_cleansing_task> on 2023-07-22 08:06:16.970985+00:00
[2023-07-22T08:07:34.697+0000] {standard_task_runner.py:57} INFO - Started process 209 to run task
[2023-07-22T08:07:34.703+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_final_project', 'spark_cleansing_task', 'manual__2023-07-22T08:06:16.970985+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_final_project.py', '--cfg-path', '/tmp/tmpfc8bn255']
[2023-07-22T08:07:34.709+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask spark_cleansing_task
[2023-07-22T08:07:34.731+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-22T08:07:34.795+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion_final_project.spark_cleansing_task manual__2023-07-22T08:06:16.970985+00:00 [running]> on host aa1a7d814135
[2023-07-22T08:07:34.933+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_final_project' AIRFLOW_CTX_TASK_ID='spark_cleansing_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-22T08:06:16.970985+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-22T08:06:16.970985+00:00'
[2023-07-22T08:07:34.942+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-22T08:07:34.944+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/spark && python3 spark-cleansing.py']
[2023-07-22T08:07:34.966+0000] {subprocess.py:86} INFO - Output:
[2023-07-22T08:07:36.688+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-07-22T08:07:42.458+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2023-07-22T08:07:42.459+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2023-07-22T08:07:42.861+0000] {subprocess.py:93} INFO - 23/07/22 08:07:42 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-07-22T08:07:44.830+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-07-22T08:07:44.839+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 209. PIDs of all processes in the group: [210, 217, 209]
[2023-07-22T08:07:44.841+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 209
[2023-07-22T08:07:44.842+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-22T08:07:44.844+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-07-22T08:07:44.870+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 205, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-22T08:07:44.879+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=data_ingestion_final_project, task_id=spark_cleansing_task, execution_date=20230722T080616, start_date=20230722T080734, end_date=20230722T080744
[2023-07-22T08:07:44.921+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 63 for task spark_cleansing_task ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(data_ingestion_final_project, spark_cleansing_task, manual__2023-07-22T08:06:16.970985+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'spark_cleansing_task', 'dag_id': 'data_ingestion_final_project', 'run_id': 'manual__2023-07-22T08:06:16.970985+00:00', 'map_index': -1, 'start_date': datetime.datetime(2023, 7, 22, 8, 7, 34, 647548, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 7, 22, 8, 7, 44, 878618, tzinfo=Timezone('UTC')), 'duration': 10}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 209)
[2023-07-22T08:07:45.180+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=210, status='terminated', started='08:07:34') (210) terminated with exit code None
[2023-07-22T08:07:45.181+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=209, status='terminated', exitcode=1, started='08:07:34') (209) terminated with exit code 1
[2023-07-22T08:07:45.395+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=217, status='terminated', started='08:07:36') (217) terminated with exit code None
