[2023-07-22T09:18:03.314+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_final_project.dbt_init_task manual__2023-07-22T09:11:20.285093+00:00 [queued]>
[2023-07-22T09:18:03.334+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_final_project.dbt_init_task manual__2023-07-22T09:11:20.285093+00:00 [queued]>
[2023-07-22T09:18:03.334+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2023-07-22T09:18:03.372+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_init_task> on 2023-07-22 09:11:20.285093+00:00
[2023-07-22T09:18:03.382+0000] {standard_task_runner.py:57} INFO - Started process 610 to run task
[2023-07-22T09:18:03.388+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_final_project', 'dbt_init_task', 'manual__2023-07-22T09:11:20.285093+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_final_project.py', '--cfg-path', '/tmp/tmpcwmjfezn']
[2023-07-22T09:18:03.393+0000] {standard_task_runner.py:85} INFO - Job 101: Subtask dbt_init_task
[2023-07-22T09:18:03.413+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-22T09:18:03.551+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion_final_project.dbt_init_task manual__2023-07-22T09:11:20.285093+00:00 [running]> on host 06435c559ff5
[2023-07-22T09:18:04.032+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_final_project' AIRFLOW_CTX_TASK_ID='dbt_init_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-22T09:11:20.285093+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-22T09:11:20.285093+00:00'
[2023-07-22T09:18:04.041+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-22T09:18:04.049+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt/bank_campaign_dwh && dbt deps && dbt seed --profiles-dir .']
[2023-07-22T09:18:04.138+0000] {subprocess.py:86} INFO - Output:
[2023-07-22T09:18:04.167+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt/bank_campaign_dwh: No such file or directory
[2023-07-22T09:18:04.170+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-22T09:18:04.195+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-22T09:18:04.202+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_final_project, task_id=dbt_init_task, execution_date=20230722T091120, start_date=20230722T091803, end_date=20230722T091804
[2023-07-22T09:18:04.250+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 101 for task dbt_init_task (Bash command failed. The command returned a non-zero exit code 1.; 610)
[2023-07-22T09:18:04.302+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-22T09:18:04.355+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
