[2023-07-22T09:21:07.330+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_final_project.dbt_init_task manual__2023-07-22T09:11:20.285093+00:00 [queued]>
[2023-07-22T09:21:07.349+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_final_project.dbt_init_task manual__2023-07-22T09:11:20.285093+00:00 [queued]>
[2023-07-22T09:21:07.350+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 4
[2023-07-22T09:21:07.383+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_init_task> on 2023-07-22 09:11:20.285093+00:00
[2023-07-22T09:21:07.392+0000] {standard_task_runner.py:57} INFO - Started process 752 to run task
[2023-07-22T09:21:07.404+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_final_project', 'dbt_init_task', 'manual__2023-07-22T09:11:20.285093+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_final_project.py', '--cfg-path', '/tmp/tmpxmkf82gx']
[2023-07-22T09:21:07.408+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask dbt_init_task
[2023-07-22T09:21:07.435+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-22T09:21:07.498+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion_final_project.dbt_init_task manual__2023-07-22T09:11:20.285093+00:00 [running]> on host 06435c559ff5
[2023-07-22T09:21:07.648+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_final_project' AIRFLOW_CTX_TASK_ID='dbt_init_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-22T09:11:20.285093+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-22T09:11:20.285093+00:00'
[2023-07-22T09:21:07.650+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-22T09:21:07.651+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt/dbt_dwh && dbt deps && dbt seed --profiles-dir .']
[2023-07-22T09:21:07.683+0000] {subprocess.py:86} INFO - Output:
[2023-07-22T09:21:07.687+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt/dbt_dwh: No such file or directory
[2023-07-22T09:21:07.688+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-22T09:21:07.709+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-22T09:21:07.719+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_final_project, task_id=dbt_init_task, execution_date=20230722T091120, start_date=20230722T092107, end_date=20230722T092107
[2023-07-22T09:21:07.739+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 102 for task dbt_init_task (Bash command failed. The command returned a non-zero exit code 1.; 752)
[2023-07-22T09:21:07.780+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-22T09:21:07.822+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
