[2023-07-27T06:05:22.821+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion-pq.dbt_init_task manual__2023-07-26T16:09:45.132166+00:00 [queued]>
[2023-07-27T06:05:22.842+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion-pq.dbt_init_task manual__2023-07-26T16:09:45.132166+00:00 [queued]>
[2023-07-27T06:05:22.842+0000] {taskinstance.py:1308} INFO - Starting attempt 14 of 15
[2023-07-27T06:05:22.876+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_init_task> on 2023-07-26 16:09:45.132166+00:00
[2023-07-27T06:05:22.889+0000] {standard_task_runner.py:57} INFO - Started process 230 to run task
[2023-07-27T06:05:22.900+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion-pq', 'dbt_init_task', 'manual__2023-07-26T16:09:45.132166+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/data_ingest_pq.py', '--cfg-path', '/tmp/tmpd4f_qyic']
[2023-07-27T06:05:22.907+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask dbt_init_task
[2023-07-27T06:05:22.954+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-27T06:05:23.049+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion-pq.dbt_init_task manual__2023-07-26T16:09:45.132166+00:00 [running]> on host 1ee8747b17e1
[2023-07-27T06:05:23.233+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion-pq' AIRFLOW_CTX_TASK_ID='dbt_init_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T16:09:45.132166+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-26T16:09:45.132166+00:00'
[2023-07-27T06:05:23.246+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-27T06:05:23.251+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt deps --profiles-dir /opt/***/dbt/marketing_dwh && dbt seed --profiles-dir /opt/***/dbt/marketing_dwh']
[2023-07-27T06:05:23.295+0000] {subprocess.py:86} INFO - Output:
[2023-07-27T06:05:31.589+0000] {subprocess.py:93} INFO - [0m06:05:31  Running with dbt=1.5.3
[2023-07-27T06:05:31.596+0000] {subprocess.py:93} INFO - [0m06:05:31  Encountered an error:
[2023-07-27T06:05:31.598+0000] {subprocess.py:93} INFO - Runtime Error
[2023-07-27T06:05:31.599+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /tmp/***tmpbtqphax0/dbt_project.yml
[2023-07-27T06:05:31.607+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2023-07-27T06:05:31.612+0000] {subprocess.py:93} INFO - 
[2023-07-27T06:05:34.268+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-07-27T06:05:34.303+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-27T06:05:34.318+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion-pq, task_id=dbt_init_task, execution_date=20230726T160945, start_date=20230727T060522, end_date=20230727T060534
[2023-07-27T06:05:34.644+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 50 for task dbt_init_task (Bash command failed. The command returned a non-zero exit code 2.; 230)
[2023-07-27T06:05:34.726+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-27T06:05:34.918+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
