[2023-07-27T05:01:18.707+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion-pq.dbt_init_task manual__2023-07-26T16:09:45.132166+00:00 [queued]>
[2023-07-27T05:01:18.723+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion-pq.dbt_init_task manual__2023-07-26T16:09:45.132166+00:00 [queued]>
[2023-07-27T05:01:18.723+0000] {taskinstance.py:1308} INFO - Starting attempt 13 of 13
[2023-07-27T05:01:18.750+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_init_task> on 2023-07-26 16:09:45.132166+00:00
[2023-07-27T05:01:18.767+0000] {standard_task_runner.py:57} INFO - Started process 543 to run task
[2023-07-27T05:01:18.773+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion-pq', 'dbt_init_task', 'manual__2023-07-26T16:09:45.132166+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/data_ingest_pq.py', '--cfg-path', '/tmp/tmp3dua9bf3']
[2023-07-27T05:01:18.778+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask dbt_init_task
[2023-07-27T05:01:18.799+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-27T05:01:18.870+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion-pq.dbt_init_task manual__2023-07-26T16:09:45.132166+00:00 [running]> on host e24602950393
[2023-07-27T05:01:19.027+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion-pq' AIRFLOW_CTX_TASK_ID='dbt_init_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T16:09:45.132166+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-26T16:09:45.132166+00:00'
[2023-07-27T05:01:19.030+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-27T05:01:19.032+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt deps --profiles-dir /opt/***/dbt/marketing_dwh && dbt seed --profiles-dir /opt/***/dbt/marketing_dwh']
[2023-07-27T05:01:19.053+0000] {subprocess.py:86} INFO - Output:
[2023-07-27T05:01:22.771+0000] {subprocess.py:93} INFO - [0m05:01:22  Running with dbt=1.5.3
[2023-07-27T05:01:22.774+0000] {subprocess.py:93} INFO - [0m05:01:22  Encountered an error:
[2023-07-27T05:01:22.775+0000] {subprocess.py:93} INFO - Runtime Error
[2023-07-27T05:01:22.775+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /tmp/***tmpa8ffdexu/dbt_project.yml
[2023-07-27T05:01:22.776+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2023-07-27T05:01:22.777+0000] {subprocess.py:93} INFO - 
[2023-07-27T05:01:24.376+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-07-27T05:01:24.393+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-27T05:01:24.399+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=data_ingestion-pq, task_id=dbt_init_task, execution_date=20230726T160945, start_date=20230727T050118, end_date=20230727T050124
[2023-07-27T05:01:24.421+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 47 for task dbt_init_task (Bash command failed. The command returned a non-zero exit code 2.; 543)
[2023-07-27T05:01:24.460+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-27T05:01:24.486+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
