[2023-07-22T10:43:27.828+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_final_project.run_dbt_task manual__2023-07-22T10:43:06.979561+00:00 [queued]>
[2023-07-22T10:43:27.888+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_final_project.run_dbt_task manual__2023-07-22T10:43:06.979561+00:00 [queued]>
[2023-07-22T10:43:27.892+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-22T10:43:27.989+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt_task> on 2023-07-22 10:43:06.979561+00:00
[2023-07-22T10:43:28.081+0000] {standard_task_runner.py:57} INFO - Started process 237 to run task
[2023-07-22T10:43:28.146+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_final_project', 'run_dbt_task', 'manual__2023-07-22T10:43:06.979561+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_final_project.py', '--cfg-path', '/tmp/tmpr9w3_3iu']
[2023-07-22T10:43:28.180+0000] {standard_task_runner.py:85} INFO - Job 108: Subtask run_dbt_task
[2023-07-22T10:43:28.336+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-22T10:43:28.681+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion_final_project.run_dbt_task manual__2023-07-22T10:43:06.979561+00:00 [running]> on host c1f03fcdfb74
[2023-07-22T10:43:29.032+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_final_project' AIRFLOW_CTX_TASK_ID='run_dbt_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-22T10:43:06.979561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-22T10:43:06.979561+00:00'
[2023-07-22T10:43:29.034+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-22T10:43:29.038+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt/dbt_dwh && dbt deps && dbt run --profiles-dir .']
[2023-07-22T10:43:29.123+0000] {subprocess.py:86} INFO - Output:
[2023-07-22T10:43:29.153+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt/dbt_dwh: No such file or directory
[2023-07-22T10:43:29.155+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-22T10:43:29.210+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-22T10:43:29.223+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_final_project, task_id=run_dbt_task, execution_date=20230722T104306, start_date=20230722T104327, end_date=20230722T104329
[2023-07-22T10:43:29.261+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 108 for task run_dbt_task (Bash command failed. The command returned a non-zero exit code 1.; 237)
[2023-07-22T10:43:29.305+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-22T10:43:29.377+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
